// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8glQuRVwinW9UG-Aw-hyqdst2WgNCK1I',
    appId: '1:947788380180:web:214fc3eb110f2078148f01',
    messagingSenderId: '947788380180',
    projectId: 'edunexus-fbcb1',
    authDomain: 'edunexus-fbcb1.firebaseapp.com',
    storageBucket: 'edunexus-fbcb1.firebasestorage.app',
    measurementId: 'G-1984R9CF88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8d30iEvGBFljPkcmQgKpnit1a9w9_b4',
    appId: '1:947788380180:android:11469e3559b8f599148f01',
    messagingSenderId: '947788380180',
    projectId: 'edunexus-fbcb1',
    storageBucket: 'edunexus-fbcb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcmchX403NKWe_X1XZ6H9egg-lL5oETy4',
    appId: '1:947788380180:ios:44f2c32c32b6f87c148f01',
    messagingSenderId: '947788380180',
    projectId: 'edunexus-fbcb1',
    storageBucket: 'edunexus-fbcb1.firebasestorage.app',
    iosClientId: '947788380180-7l4019m0udesve0tjjfaknah0q09j7sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.edunexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcmchX403NKWe_X1XZ6H9egg-lL5oETy4',
    appId: '1:947788380180:ios:44f2c32c32b6f87c148f01',
    messagingSenderId: '947788380180',
    projectId: 'edunexus-fbcb1',
    storageBucket: 'edunexus-fbcb1.firebasestorage.app',
    iosClientId: '947788380180-7l4019m0udesve0tjjfaknah0q09j7sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.edunexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8glQuRVwinW9UG-Aw-hyqdst2WgNCK1I',
    appId: '1:947788380180:web:881eb3ffe6fc3c1e148f01',
    messagingSenderId: '947788380180',
    projectId: 'edunexus-fbcb1',
    authDomain: 'edunexus-fbcb1.firebaseapp.com',
    storageBucket: 'edunexus-fbcb1.firebasestorage.app',
    measurementId: 'G-XHM0LL4JGD',
  );
}
