import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:pdf/pdf.dart';
import 'package:flutter_tts/flutter_tts.dart'; // Naya Import

class SavedNotesScreen extends StatefulWidget {
  const SavedNotesScreen({super.key});

  @override
  State<SavedNotesScreen> createState() => _SavedNotesScreenState();
}

class _SavedNotesScreenState extends State<SavedNotesScreen> {
  final FlutterTts flutterTts = FlutterTts();

  // PDF Generate Function
  Future<void> _generateAndDownloadPdf(String title, String content) async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.Page(
        build: (pw.Context context) => pw.Padding(
          padding: const pw.EdgeInsets.all(20),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text("EduNexus - Digital Notes", style: pw.TextStyle(fontSize: 12, color: PdfColors.blue)),
              pw.SizedBox(height: 10),
              pw.Text(title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              pw.Divider(thickness: 2),
              pw.SizedBox(height: 20),
              pw.Text(content, style: const pw.TextStyle(fontSize: 14)),
              pw.Spacer(),
              pw.Divider(),
              pw.Text("Generated by Mayuresh Khanvilkar", style: const pw.TextStyle(fontSize: 10)),
            ],
          ),
        ),
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) => pdf.save(),
      name: '${title.replaceAll(' ', '_')}.pdf',
    );
  }

  // --- TTS Listen Function ---
  Future<void> _listenToNote(String content) async {
    await flutterTts.setLanguage("en-US");
    await flutterTts.setPitch(1.0);
    await flutterTts.speak(content);
  }

  @override
  Widget build(BuildContext context) {
    final user = FirebaseAuth.instance.currentUser;

    return Scaffold(
      backgroundColor: const Color(0xFFF8F9FE),
      appBar: AppBar(
        title: Text("My Saved Notes", style: GoogleFonts.poppins(fontWeight: FontWeight.bold)),
        backgroundColor: Colors.white, foregroundColor: Colors.black, elevation: 0.5,
      ),
      body: StreamBuilder<QuerySnapshot>(
        stream: FirebaseFirestore.instance
            .collection('notes')
            .where('userId', isEqualTo: user?.uid)
            .orderBy('createdAt', descending: true)
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) return const Center(child: CircularProgressIndicator());

          var docs = snapshot.data!.docs;
          if (docs.isEmpty) return _buildEmptyState();

          return ListView.builder(
            padding: const EdgeInsets.all(15),
            itemCount: docs.length,
            itemBuilder: (context, index) {
              var note = docs[index];
              Map<String, dynamic> data = note.data() as Map<String, dynamic>;
              String title = data['title'] ?? "Untitled";
              String content = data['text'] ?? "";
              bool isAudio = data['type'] == 'audio'; // Type detect karna

              return Container(
                margin: const EdgeInsets.only(bottom: 12),
                decoration: BoxDecoration(
                  color: Colors.white, borderRadius: BorderRadius.circular(18),
                  boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 10)],
                ),
                child: ListTile(
                  onTap: () => _showNoteDetail(context, title, content, isAudio),
                  leading: CircleAvatar(
                    backgroundColor: isAudio ? Colors.red.withOpacity(0.1) : Colors.blue.withOpacity(0.1),
                    child: Icon(isAudio ? Icons.mic : Icons.description, color: isAudio ? Colors.red : Colors.blue),
                  ),
                  title: Text(title, style: GoogleFonts.poppins(fontWeight: FontWeight.w600, fontSize: 14)),
                  subtitle: Text(content, maxLines: 1, overflow: TextOverflow.ellipsis, style: const TextStyle(fontSize: 12)),
                  trailing: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      if (isAudio) IconButton(icon: const Icon(Icons.volume_up, color: Colors.orange), onPressed: () => _listenToNote(content)),
                      IconButton(icon: const Icon(Icons.picture_as_pdf, color: Colors.redAccent), onPressed: () => _generateAndDownloadPdf(title, content)),
                    ],
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
        Icon(Icons.notes_outlined, size: 80, color: Colors.grey[300]),
        Text("No notes saved yet!", style: GoogleFonts.poppins(color: Colors.grey)),
      ]),
    );
  }

  // --- DETAIL VIEW WITH PLAY BUTTON ---
  void _showNoteDetail(BuildContext context, String title, String content, bool isAudio) {
    showModalBottomSheet(
      context: context, isScrollControlled: true,
      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(25))),
      builder: (context) => Container(
        padding: const EdgeInsets.all(25),
        height: MediaQuery.of(context).size.height * 0.75,
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
            Expanded(child: Text(title, style: GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.bold))),
            if (isAudio) IconButton(icon: const Icon(Icons.play_circle_fill, color: Colors.redAccent, size: 40), onPressed: () => _listenToNote(content)),
          ]),
          const Divider(height: 30),
          Expanded(child: SingleChildScrollView(child: Text(content, style: GoogleFonts.poppins(fontSize: 14, height: 1.6)))),
          const SizedBox(height: 20),
          ElevatedButton.icon(
            onPressed: () => _generateAndDownloadPdf(title, content),
            icon: const Icon(Icons.download, color: Colors.white),
            label: const Text("Export as PDF", style: TextStyle(color: Colors.white)),
            style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF2D5AF0), minimumSize: const Size(double.infinity, 50), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15))),
          ),
        ]),
      ),
    );
  }
}